# Generated by Django 5.2.7 on 2025-10-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('versionNumber', models.AutoField(primary_key=True, serialize=False)),
                ('frontPageHeader', models.CharField(blank=True, max_length=140)),
                ('frontPageDescription', models.TextField(blank=True)),
                ('stepParentAdoptionDescription', models.TextField(blank=True)),
                ('adultAdoptionDescription', models.TextField(blank=True)),
                ('guardianshipDescription', models.TextField(blank=True)),
                ('nameTitle', models.CharField(blank=True, max_length=120)),
                ('aboutMeDescription', models.TextField(blank=True)),
                ('officeLocation', models.CharField(blank=True, max_length=200)),
                ('footerDescription', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
