# Generated by Django 5.2.7 on 2025-10-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='guardianshipToAdoptionDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='independentAdoptionDescription',
            field=models.TextField(blank=True),
        ),
    ]
