# Generated by Django 5.2.7 on 2026-02-06 00:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_websitecontent_guardianshiptoadoptiondescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Body')),
            ],
        ),
    ]
