# Generated by Django 5.2.7 on 2026-02-06 01:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0003_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='aboutMeDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='adultAdoptionDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='footerDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='frontPageDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='guardianshipDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='guardianshipToAdoptionDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='independentAdoptionDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='stepParentAdoptionDescription',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
