# Generated by Django 5.2.7 on 2025-10-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('type', models.CharField(choices=[('APPT_CONFIRM', 'Appointment Confirmation'), ('APPT_REMINDER', 'Appointment Reminder'), ('INVOICE_ISSUED', 'Invoice Issued'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('PASSWORD_RESET', 'Password Reset')], max_length=30)),
                ('sent_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=10)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user')),
            ],
        ),
    ]
