# Generated by Django 5.2.7 on 2025-10-24 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('type', models.CharField(choices=[('APPT_CONFIRM', 'Appointment Confirmation'), ('APPT_REMINDER', 'Appointment Reminder'), ('INVOICE_ISSUED', 'Invoice Issued'), ('PAYMENT_RECEIPT', 'Payment Receipt'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='SENT', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('target_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('target_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['channel', 'status'], name='appointment_channel_609e66_idx'), models.Index(fields=['type', 'sent_at'], name='appointment_type_93550e_idx')],
            },
        ),
    ]
