# Generated by Django 5.2.7 on 2025-11-12 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='appointments',
            name='calendly_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='calendly_event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='calendly_event_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='calendly_event_uri',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='calendly_host_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='calendly_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='calendly_location_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='calendly_organization_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='calendly_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendly_invitee_uri', models.URLField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='active', max_length=50)),
                ('canceled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('reschedule_url', models.URLField(blank=True, null=True)),
                ('calendly_created_at', models.DateTimeField(blank=True, null=True)),
                ('calendly_updated_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='appointments.appointments')),
            ],
        ),
    ]
