# Generated by Django 5.2.7 on 2025-11-12 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
