# Generated by Django 5.2.7 on 2025-11-12 08:09

import appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointments_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='confirmation_number',
            field=models.CharField(blank=True, default=appointments.models.Appointments.create_confirmation_number, max_length=8, null=True, unique=True),
        ),
    ]
