# Generated by Django 5.2.7 on 2025-10-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoices',
        ),
    ]
