# Generated by Django 5.2.7 on 2026-02-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_invoice_status_and_webhook_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hosted_invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
